query Service($id: ID!){
    servicio(id: $id){
        id
        nombre
        contenido
        whatsapp
        fotografias{
            imagen{
                url
            }
        }
    }
}