query Products{
    products{
        id
        nombre
        descripcion
        cover{
            url
        }
        fotos{
            imagen{
                url
            }
        }
        precio
    }
}