query Category($id: ID!){
    secategoria(id: $id){
        id
        nombre
        servicios{
            id
            nombre
            portada{
                url
            }
        }
    }
}